### ISSUE TITLE
error with VERSION

### ISSUE THREAD

**Issue by gmicroul** [sailfishos/mic#21]
Installed /usr/lib/python3.10/site-packages/mic-0.14-py3.10.egg
Processing dependencies for mic==0.14
Finished processing dependencies for mic==0.14
Traceback (most recent call last):
  File "/usr/bin/mic", line 4, in <module>
    __import__('pkg_resources').run_script('mic==0.14', 'mic')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mic==0.14' distribution was not found and is required by the application
Error: Process completed with exit code 1.

**Comment by gmicroul** [comment]
fixed
